# kube-prometheus-stack configuration for development

kube-prometheus-stack:
  # Prometheus configuration
  prometheus:
    prometheusSpec:
      # Storage configuration
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3  # EKS storage class
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
      
      # Resource limits (development-sized)
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 512Mi
      
      # Data retention (shorter for development)
      retention: 7d
      retentionSize: 4GB
      
      # Additional scrape configs can be added here
      additionalScrapeConfigs: []

  # Grafana configuration
  grafana:
    enabled: true
    
    # Admin password for development
    adminPassword: "dev-admin-password"
    
    # Grafana storage
    persistence:
      enabled: true
      storageClassName: gp3  # EKS storage class
      size: 1Gi
    
    # Resource limits (development-sized)
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    
    # Service configuration
    service:
      type: ClusterIP
      port: 80
    
    # Ingress for easy access (optional)
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      hosts:
        - grafana.dev.local
      path: /
      pathType: Prefix
      tls: []
    
    # Grafana configuration
    grafana.ini:
      server:
        root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
        serve_from_sub_path: true
      auth.anonymous:
        enabled: false
      analytics:
        check_for_updates: false
        reporting_enabled: false

  # AlertManager configuration
  alertmanager:
    alertmanagerSpec:
      # Storage configuration (smaller for development)
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3  # EKS storage class
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 500Mi
      
      # Resource limits (development-sized)
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi

  # Node Exporter configuration
  nodeExporter:
    enabled: true

  # Kube State Metrics configuration
  kubeStateMetrics:
    enabled: true

  # Prometheus Operator configuration
  prometheusOperator:
    enabled: true
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi

  # Default service monitors and alerting rules
  defaultRules:
    create: true
    rules:
      alertmanager: true
      etcd: true
      configReloaders: true
      general: true
      k8s: true
      kubeApiserverAvailability: true
      kubeApiserverBurnrate: true
      kubeApiserverHistogram: true
      kubeApiserverSlos: true
      kubelet: true
      kubeProxy: true
      kubePrometheusGeneral: true
      kubePrometheusNodeRecording: true
      kubernetesApps: true
      kubernetesResources: true
      kubernetesStorage: true
      kubernetesSystem: true
      kubeScheduler: true
      kubeStateMetrics: true
      network: true
      node: true
      nodeExporterAlerting: true
      nodeExporterRecording: true
      prometheus: true
      prometheusOperator: true