apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  description: Project for cluster-level addons and infrastructure components
  
  sourceRepos:
    - 'https://github.com/savak1990/bg-argocd-gitops.git'
    - 'https://prometheus-community.github.io/helm-charts'
  
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: ''
      kind: ClusterRole
    - group: ''
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: storage.k8s.io
      kind: StorageClass
    - group: apiregistration.k8s.io
      kind: APIService
  
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: apps
      kind: '*'
    - group: networking.k8s.io
      kind: '*'
    - group: monitoring.coreos.com
      kind: '*'
    - group: cert-manager.io
      kind: '*'
  
  roles:
    - name: admin
      description: Full access to cluster addons
      policies:
        - p, proj:cluster-addons:admin, applications, *, cluster-addons/*, allow
        - p, proj:cluster-addons:admin, repositories, *, *, allow
      groups:
        - cluster-admins
    
    - name: readonly
      description: Read-only access to cluster addons
      policies:
        - p, proj:cluster-addons:readonly, applications, get, cluster-addons/*, allow
      groups:
        - developers