aws-ebs-csi-driver:
  # Enable the EBS CSI driver
  enabled: true
  
  # Controller configuration
  controller:
    replicaCount: 2
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    
    # Service account for IRSA (IAM Roles for Service Accounts)
    serviceAccount:
      create: true
      name: ebs-csi-controller-sa
      annotations:
        # Add your IAM role ARN here if using IRSA
        # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/EBS_CSI_DriverRole
  
  # Node configuration
  node:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    
    serviceAccount:
      create: true
      name: ebs-csi-node-sa
  
  # Storage classes to create
  storageClasses:
    - name: gp3
      annotations:
        storageclass.kubernetes.io/is-default-class: "true"
      parameters:
        type: gp3
        fsType: ext4
        encrypted: "true"
      reclaimPolicy: Delete
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
