# metrics-server configuration for EKS

metrics-server:
  # Resource configuration
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 200m
      memory: 400Mi

  # Additional arguments for EKS
  args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP

  # Default service configuration (don't override ports)
  # The chart will use the correct defaults

  # Replica count (single replica for development)
  replicas: 1

  # Host network (disabled for security)
  hostNetwork:
    enabled: false

  # Service account
  serviceAccount:
    create: true
    name: ""
    annotations: {}

  # RBAC
  rbac:
    create: true

  # API service configuration
  apiService:
    create: true
    annotations: {}
    insecureSkipTLSVerify: true  # For development with self-signed certs